# Generated by Django 5.2.3 on 2025-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('annee_arrivee', models.DateField()),
                ('statut', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='photos/admins/')),
            ],
            options={
                'db_table': 'admin',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['email'], name='admin_email_07aef7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.AutoField(primary_key=True, serialize=False)),
                ('siret', models.CharField(max_length=14)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('annee_arrivee', models.DateField(blank=True, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('acces_templates', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'entreprise',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['email'], name='entreprise_email_6818a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='photos/professionnels/')),
                ('classement', models.PositiveIntegerField(blank=True, null=True)),
                ('annee_arrivee', models.DateField()),
                ('ynnovass_account', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'professionnel',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['email'], name='professionn_email_633464_idx')],
            },
        ),
    ]
