# Generated by Django 5.2.3 on 2025-07-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonnement', models.CharField(choices=[('premium', 'Premium'), ('basic', 'Basic')], default='basic', max_length=50)),
                ('debut', models.DateField(auto_now_add=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('acces_templates', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='authentication.entreprise')),
            ],
        ),
    ]
