# Generated by Django 5.2.3 on 2025-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField()),
                ('classement', models.IntegerField()),
                ('annee_arrivee', models.DateField(blank=True, null=True)),
                ('mdp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'professionnel',
                'managed': False,
            },
        ),
    ]
